### ISSUE TITLE
Nye endringer på masterbranch trigger ikke github-action for publisering av nytt bygg

### ISSUE THREAD

**Issue by JonasJore** [SpareBank1/jobbsb1#195]

**Comment by antidecaf** [comment]
Kan du utdype? Jeg merget noe som ble publisert som vanlig senest på onsdag.

**Comment by JonasJore** [comment]
Jeg oppdaterte en `.md` fil her: 236990acc930cbb60cd84839f076d31e57e45991 og det så ikke ut som at gh action for å publisere nye endringer ble kjørt.
