### ISSUE TITLE
txt is not defined

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/jobbsb1#228]
Bygget har kjørt rødt i noen dager, med denne feilmeldinga:

![image](https://github.com/SpareBank1/jobbsb1/assets/463847/d7baae5e-fdba-4a62-ab17-85cdcb332c9c)

Tilsynelatende relatert til empati-siden som nylig har blitt lagt til. Har du mulighet til å kikke på dette, @kariannekristiansen?

**Comment by kariannekristiansen** [comment]
Ja, sorry. Skal se på det i dag ☺️

**Comment by kariannekristiansen** [comment]
Kjørte grønt nå ☺️

**Comment by antidecaf** [comment]
Perfekt, takk!
