### ISSUE TITLE
Custom domain blir slettet ved hver deploy

### ISSUE THREAD

**Issue by sconrads** [SpareBank1/jobbsb1#50]
Tips:
Also gh-pages will overwrite the CNAME file, because it just always pushes everything from the build folder to the gh-pages branch.
A simple workaround for this problem is to add a CNAME file with the custom domain inside the public folder in your project and it will be copied to the build and deployed.
Fra https://github.com/facebook/create-react-app/issues/654

**Comment by antidecaf** [comment]
Fikset via #51

**Comment by antidecaf** [comment]
Dette fortsetter visst å skje selv om CNAME tilsynelatende er i orden.

**Comment by sconrads** [comment]
Ser ut til å være #64 som er skyld i dette. Bygget feiler på Travis:
`error Building static HTML failed for path "/ux1"
See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html
  34 |             </GridCol>
  35 |             <GridCol sm={{ cols: 12 }} md={{ cols: 4 }} lg={{ cols: 4 }} end={true}>
> 36 |               <img src={frontmatter.image.childImageSharp.fixed.src} alt={frontmatter.title} className="sb1-markdown-page__image" />
     |                                           ^
  37 |             </GridCol>
  38 |           </GridRow>
  39 |         </Grid>
  WebpackError: TypeError: Cannot read property 'childImageSharp' of null
  
  - pageTemplate.js:36 Template
    lib/src/templates/pageTemplate.js:36:43
  
  - bootstrap:22 c
    lib/webpack/bootstrap:22:1
  
  - bootstrap:25 Sa
    lib/webpack/bootstrap:25:1
  
  - bootstrap:30 a.render
    lib/webpack/bootstrap:30:1
  
  - bootstrap:30 a.read
    lib/webpack/bootstrap:30:1
  
  - bootstrap:42 renderToString
    lib/webpack/bootstrap:42:1
[0m  
  - static-entry.js:206 Module../.cache/static-entry.js.__webpack_exports__.defa    ult
    lib/.cache/static-entry.js:206:18
  
  - bootstrap:24 Promise
    lib/webpack/bootstrap:24:1
  
  
  - gatsby-browser-entry.js:15 Promise._resolveFromExecutor
    lib/.cache/gatsby-browser-entry.js:15:26
  
  - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1
  
  
  - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1
  
  - bootstrap:50 MappingPromiseArray._promiseFulfilled
    lib/webpack/bootstrap:50:1
  
  - api-runner-ssr.js:6 MappingPromiseArray.PromiseArray._iterate
    lib/.cache/api-runner-ssr.js:6:16
  
  - bootstrap:67 MappingPromiseArray.init
    lib/webpack/bootstrap:67:1
  
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jobbsb1@0.1.0 deploy: `rm -rf .cache/* && gatsby build && gh-pages -d public`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jobbsb1@0.1.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-05-11T12_47_27_968Z-debug.log
dpl_0
2.32s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.10.8
Parsing documentation for dpl-1.10.8
Installing ri documentation for dpl-1.10.8
Done installing documentation for dpl after 0 seconds
`

**Comment by antidecaf** [comment]
Hvor ser du dette @sconrads? Jeg finner bare grønne bygg på travis.

**Comment by sconrads** [comment]
Jobben går grønn selv om bygget feiler... Jeg ser det i loggen til travis
og lokalt.
